<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <title>News</title>
</head>
<body>


<form action="sendlogin" method="POST">
    <input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"/>
    <input type="text" placeholder="Mail" name="mail" id="mail">
    <input type="password" placeholder="Password" name="password" id="password">
    <button type="submit"> Posalji </button>

</form>
<a href="/">Home</a>

</body>
<script src="/js/jquery-3.6.0.min.js" type="text/javascript">
</script>
<script src="js/main.js" type="text/javascript">
</script>
</html>


