<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<?php

 foreach ($new as $value){
     $token=csrf_token();

    echo "  <h1>$value->titlee</h1>
    
    <p>$value->description</p>
    
    <h3>Subscribe for this new</h3>
    <form id ='forma' action='/subscribenew' method='post'>
    

    ";

}

?>

<input type='hidden' name='csrf_token' value=<?=csrf_token()?>>
<input type="text"  class="form-control" name="submail" id="mail" placeholder="Email" aria-label="Email" aria-describedby="addon-wrapping">'
`
<?php
foreach ($new as $value){
   echo"  <button type='submit' value='$value->idnews' name='new'>,cmdd</button>";

}?>



</form>

</body>
</html>
